edition = "2018"
version = "Two"
normalize_doc_attributes = true
indent_style = "Block"
reorder_imports = true
merge_imports = true
empty_item_single_line = false
where_single_line = true
format_strings = true
normalize_comments = true
reorder_modules = true
reorder_impl_items = true
struct_field_align_threshold = 20
use_try_shorthand = true
format_code_in_doc_comments = true
